// <auto-generated />
namespace QLCV.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTableAccountTokenlogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableAccountTokenlogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201904151537316_addTableAccount-Tokenlogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
